# Generated by Django 4.1.1 on 2022-09-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
