# Generated by Django 4.1.1 on 2022-09-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
