# Generated by Django 4.1.1 on 2022-09-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
