# Generated by Django 4.1.1 on 2022-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('post_sno', models.IntegerField()),
            ],
        ),
    ]
