# Generated by Django 3.1.5 on 2021-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
